version: '3.8'

services:
  crewai-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: crewai-dashboard-pro
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      # Example: If you have a backend API, you can pass its URL here
      # VITE_CREWAI_API_URL: http://backend:8000/api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crewai.rule=Host(`dashboard.crewai.local`)"
      - "traefik.http.services.crewai.loadbalancer.server.port=80"
    networks:
      - app-network

  # Optional: Add a reverse proxy
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  crewai-data:
    driver: local
